Repository spatialos/UnrealGDKReferenceProject, pull requests merged in 2019-10, with the labels that each got.

#6 Added spatialos.DatabaseSyncWorker.worker.json
  spatial/provided/spatialos.DatabaseSyncWorker.worker.json
Labels: jira/no-ticket, size/M

#7 Add support for Improbable Online Services and a custom matcher
  CustomMatcher/Matcher.cs
  CustomMatcher/README.md
  Game/Config/DefaultEngine.ini
  Game/Content/Controllers/BP_DeploymentController.uasset
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/Controllers/Components/Menus.uasset
  Game/Content/UI/Blueprints/BP_AuthScreen.uasset
  Game/Content/UI/Blueprints/BP_CorridoorShooter_LoginScreen.uasset
  Game/Content/UI/Blueprints/BP_ExternalLogin.uasset
  Game/Content/UI/Blueprints/BP_GDK_HUD.uasset
  Game/Content/UI/Blueprints/BP_HUD_CorridorShooter.uasset
  Game/Content/UI/Blueprints/Deployments/BP_HUD_Deployments.uasset
  Game/Content/UI/OnlinePlayers/Blueprints/BP_OnlinePlayerScrollBox.uasset
  Game/Content/UI/OnlinePlayers/Blueprints/BP_OnlinePlayerWidget.uasset
  Game/Content/UI/OnlinePlayers/Blueprints/BP_OnlinePlayersScreen.uasset
  Game/Content/UI/Party/WB_CurrentPartyBox.uasset
  Game/Content/UI/Party/WB_CurrentPartyPanel.uasset
  Game/Content/UI/Party/WB_PartyInviteBox.uasset
  Game/Content/UI/Party/WB_PartyInvitePanel.uasset
  Game/Content/UI/Party/WB_PartyInviteWidget.uasset
  Game/Content/UI/Party/WB_PartyMemberWidget.uasset
  Game/Content/UI/Party/WB_PartyScreen.uasset
  Game/Content/UI/PartyInvites/BP_PartyInviteBox.uasset
  Game/Content/UI/PartyInvites/BP_PartyInvitePanel.uasset
  Game/Content/UI/PartyInvites/BP_PartyInviteWidget.uasset
  Game/GDKShooter.uproject
  Game/Source/GDKShooter/ExternalSchemaCodegen/ExternalSchemaHelperFunctions.cpp
  Game/Source/GDKShooter/ExternalSchemaCodegen/ExternalSchemaHelperFunctions.h
  Game/Source/GDKShooter/GDKShooter.Build.cs
  Game/Source/GDKShooter/Private/Controllers/PartySystem.cpp
  Game/Source/GDKShooter/Private/Controllers/PlayerIdentity.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/Game/CorridorShooterGameInstance.cpp
  Game/Source/GDKShooter/Private/Game/OnlineServicesLibrary.cpp
  Game/Source/GDKShooter/Public/Controllers/PartySystem.h
  Game/Source/GDKShooter/Public/Controllers/PlayerIdentity.h
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
  Game/Source/GDKShooter/Public/Game/CorridorShooterGameInstance.h
  Game/Source/GDKShooter/Public/Game/OnlineServicesLibrary.h
  README.md
  spatial/default_launch.json
Labels: jira/no-ticket, size/XXL

#10 Fix playfab plugin naming in build.cs
  Game/Source/GDKShooter/GDKShooter.Build.cs
Labels: jira/no-ticket, size/XS

#11 replace X to accept with an actual accept button
  Game/Content/UI/Party/WB_PartyInvitePanel.uasset
  Game/Content/UI/Party/WB_PartyInviteWidget.uasset
Labels: jira/no-ticket, size/XS

#12 Fix some bugs with the proceed button
  Game/Content/UI/Party/WB_PartyScreen.uasset
Labels: jira/no-ticket, size/XS

#13 Add explanation and potential workarounds for current custom matcher issues
  CustomMatcher/README.md
Labels: jira/no-ticket, size/XS

#9 Add safety for 'this' capture in lambdas.
  Game/Source/GDKShooter/Private/Controllers/PartySystem.cpp
  Game/Source/GDKShooter/Private/Controllers/PlayerIdentity.cpp
Labels: jira/no-ticket, size/M
